### PR TITLE
Tensorflow Quantization - Xilinx ml-suite

### PR DESCRIPTION
**Pull request by mahinlma**
Added scripts for Tensorflow Quantization. 
Added 3 argument:
 - **framework**  for passing framework detail (tf/caffe)
 - **input_layer** for passing TF graph input layer name
 - **output_layer** for passing TF graph output layer name

### CODE REVIEW

**Comment by mahinlma** [comment]
Fixed conflicts with recent changes.

**Comment by wilderfield** [comment]
Hey, Can you please explain what you are trying to add? 

We are in the process of integrating Deephi Caffe and Tensorflow quantizers. The older python based quantizers are being retired. This release gives a caffe quantizer via the Docker container. Next release should bring back Tensorflow quantization.

**Comment by mahinlma** [comment]
Hi @wilderfield, 

When I tried to quantize TF model, got empty result from quantize.pyc.
because quantize() function in quantize.pyc doesn't have script to initiate/call TF quantizer. 
So I just updated that script and **added framework argument** to pass Framework detail (caffe / tensorflow),
And added **2 more arguments** to pass **input and output layer name** of the tensorflow model.

changed the class name from **CaffeFrontend** to **Frontend**
Updated framework, input_layer and output_layer args with Frontend class

**Comment by mahinlma** [comment]
Command format example:

python quantize.py --framework tf --weights /home/xpac/vcu1525/ml-suite/models/tensorflow/bvlc_googlenet/fp32/bvlc_googlenet.pb    --dims 3,112,112 --bitwidths 8,8,8 --input_scale 1.0 --calibration_size 8 --calibration_indices 0,1,2,3,4,5,6,7 --framework tf --input_layer data --output_layer prob --calibration_directory /home/xpac/exp/Mahi/data/

**Comment by wilderfield** [comment]
@mahinlma thanks for working with ml-suite! Your contribution would have been warmly received, however, right now we are on a path to replace that old quantizer. 

https://www.xilinx.com/news/press/2018/xilinx-announces-the-acquisition-of-deephi-tech.html

Last year Xilinx bought this company, who's main technology was quantization and pruning tools. Their quantizer was much more robust compared to ours. We have been integrating their quantizer into our tool flow for several months now. We are integrating the tensorflow version as we speak. 

xfdnn/tools/quantize will be gone for the future releases.

**Pull request closed without merging**
